### ISSUE TITLE
Update namelists

### ISSUE THREAD

**Issue by atb299** [jdha/ORCHESTRA#16]
Add Simmons et al block to namelists

**Comment by atb299** [comment]
@jdha this issue refers to the "my_src_tracers" branch I just created. I can't see a way to link an issue to a branch.

**Comment by jdha** [comment]
@atb299 - the only way (that I know off) is if you open a PR on the branch - then you can link the issue to the PR. If that doesn't make much sense, we can run through it on Monday.
